server:
  port: 8091
  tomcat:
    max-threads: 200
    accept-count: 200
    connection-timeout: 20000
  compression:
    enabled: true
    mime-types: video/mp4
    min-response-size: 1024
  servlet:
    context-path: /tsad/media
spring:
  application:
    name: media-server
    source-path:
      image: src/main/resources/source/image
      audio: src/main/resources/source/audio
      video: src/main/resources/source/video
      document: src/main/resources/source/document
      web-resource: src/main/resources/web-resource
    source:
      video:
        content-size: 1 # MB
security:
  jwt-token:
    secret: f7RDrRhuJo6McWeCQlBrY68SnjX8JT8r # 256-bit key
  ip-token:
    secret: 120PD9V0DKXZEUQ4 # 16-char key (128-bit)
  token:
    expire-unit: # day, hour, minute, second
      image: second
      audio: second
      video: second
      document: second
    expire-duration:
      image: 120
      audio: 60
      video: 60
      document: 60
webservicedb:
  datasource:
    poolName: webservicedb-pool
    connectionTimeOut: 10000
    maximumPoolSize: 20
    jdbcUrl: jdbc:postgresql://localhost:5432/tsad_local_db
    username: tsad_local
    password: tsad-24@local
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /tsad/media/v3/api-docs
    config-url: /tsad/media/v3/api-docs/swagger-config
    disable-swagger-default-url: true